name: php basic website ci workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: ' 10 * * 0'
  workflow_dispatch:

jobs:
    bulids:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             uses: actions/checkout@v3
           - name: setting up php
             uses: shivammathur/setup-php@v2
             with:
               php-version: '8.2'
                 